Small translation changes
tienducle/Stardew-Valley-Expanded-DE-Translation pull request #11
Opened 2024-10-20 15:53 UTC by Archer7x

Kleine Übersetzungsaänderungen die mir aufgefallen sind. (Tag 0.0.30 existiert bereits?)

2024-10-20 16:27 UTC, Tschubakaa commented on Stardew Valley Expanded/[CP] Stardew Valley Expanded/i18n/de.json
> +  "Name.Apples": "Äpfel",
"Apples" ist der Name eines Junimos. Es könnte besser sein, den Namen im Original zu belassen.

2024-10-20 16:34 UTC, Archer7x commented on Stardew Valley Expanded/[CP] Stardew Valley Expanded/i18n/de.json
> +  "Name.Apples": "Äpfel",
Achso. Dann lassen wir das so.

2024-10-27 14:02 UTC, tienducle requested changes

2024-10-27 14:02 UTC, tienducle commented on Stardew Valley Expanded/[CP] Stardew Valley Expanded/i18n/de.json
> +  "Claire.MarriageDialogue.012": "%%kid1 hat so früh angefangen zu laufen... vielleicht wird es wie seine Mutter Tänzer?$1#$e#%Du umarmst Claire.#$e#Hehe...$7",
Hier muss ein '%' wieder weg
```suggestion
  "Claire.MarriageDialogue.012": "%kid1 hat so früh angefangen zu laufen... vielleicht wird es wie seine Mutter Tänzer?$1#$e#%Du umarmst Claire.#$e#Hehe...$7",
```

2024-10-27 16:01 UTC, Archer7x commented on Stardew Valley Expanded/[CP] Stardew Valley Expanded/i18n/de.json
> +  "Claire.MarriageDialogue.012": "%%kid1 hat so früh angefangen zu laufen... vielleicht wird es wie seine Mutter Tänzer?$1#$e#%Du umarmst Claire.#$e#Hehe...$7",
Stimmt, werde ich ändern, danke!

2024-11-02 11:58 UTC, merged